# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 18:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcctBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('entry', models.IntegerField()),
                ('is_deposit', models.BooleanField(default=1)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('memo_or_note', models.CharField(max_length=35)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
