# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 22:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcctBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.IntegerField()),
                ('credit', models.BooleanField(default=1)),
                ('debit', models.BooleanField(default=0)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('account', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='acctbalance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ironapp.Customer'),
        ),
    ]
