# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ironapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acctbalance',
            old_name='name',
            new_name='memo_or_note',
        ),
    ]
