# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acctbalance',
            name='name',
            field=models.CharField(default=2, max_length=35),
            preserve_default=False,
        ),
    ]
