# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironapp', '0002_auto_20160711_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='acctbalance',
            name='account_number',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
