# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 13:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ironapp', '0004_auto_20160713_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('transfer_amount', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('memo_or_note', models.CharField(max_length=35)),
            ],
        ),
        migrations.AddField(
            model_name='acctbalance',
            name='is_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ironapp.AcctBalance'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
