# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ironapp', '0007_auto_20160713_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acctbalance',
            name='transfer_amount',
        ),
    ]
